FROM python:3.10.12

WORKDIR /app

COPY requirements.txt ./

RUN pip3 install -r requirements.txt

COPY . .

WORKDIR /app/marzbanBot/src

ENV BACKEND_URL="http://167.99.248.242:3001/api"

EXPOSE 8000

CMD ["python","bot.py"]